### ISSUE TITLE
Fix description 2022 -> 2024

### ISSUE THREAD

**Issue by juanitorduz** [drbenvincent/pydata-global-2024#1]
@drbenvincent I think you have a typo ;) 

![image](https://github.com/user-attachments/assets/c09460a6-c62b-4a32-9f7b-69ffc18ff186)

**Comment by drbenvincent** [comment]
Done. Thanks!
 
<img width="336" alt="Screenshot 2024-12-06 at 12 04 08" src="https://github.com/user-attachments/assets/efa9d097-dbd5-4317-89b1-20d1c2500554">
